name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
    - name: ESLint checker
      uses: ninosaurus/eslint-check@v5.3.1
      with:
        # github security stoken
        repo-token: ${{secrets.GITHUB_TOKEN}}
        # relative directory to node_modules
        custom-directory: "./"
        # relative path to eslint confnig file eg. .eslintrc
        eslint-config-path: ".eslintrc.json"
