# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: ESLint checker
      uses: ninosaurus/eslint-check@v5.3.1
      with:
        # github security stoken
        repo-token: ${{secrets.GITHUB_TOKEN}}
        # relative directory to node_modules
        custom-directory: "./"
        # relative path to eslint config file eg. .eslintrc
        eslint-config-path: "./config/.eslintrc.json"
